[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[scheduled.functions]]
  name = "monthly-reaudit"
  cron = "0 9 1 * *"
